### ISSUE TITLE
the quantized bit width

### ISSUE THREAD

**Issue by xiaxin1998** [Aaronhuang-778/SliM-LLM#3]
Hello,

Can I know how to get the quantized bit-width for every parameter in W for llama 7b by running your codes?
Is this feasible to use your part of method to compute and save the quantization bit-width of each parameter in the weight matrix and use them to do other tasks?

Thank you very much!

**Comment by Aaronhuang-778** [comment]
Hi Xin@xiaxin1998,

Yes, you can just run the following script to get the quantized performance of llama-7b.
`python run.py \
 huggyllama/llama-7b wikitext2 3bit --groupsize 128 \
--device "cuda:0" --tasks piqa,arc_easy,arc_challenge,boolq,hellaswag,winogrande`

SliM-LLM will automatically generate the bit-width allocation file in this path `block_configurations = f'../SliM-LLM_group-precision/block_precision_{args.groupsize}_{args.low_quant_method}/{net}.pt'`.  

And for convenience, you can simply check this huggingface repo (https://huggingface.co/AaronHuangWei/SliM-LLM_group-precision/tree/main) to download the pre-generated bit-width of llama-7b. We provide the 2-bit and 3-bit results of llama-7b with group_size=128.

**Comment by xiaxin1998** [comment]
Thanks for your quick reply. I will have a try!

**Comment by sidhantls** [comment]
@Aaronhuang-778  how do I use the mixed precision data(https://huggingface.co/AaronHuangWei/SliM-LLM_group-precision/tree/main/block_precision_128_3bit)?  i expected the data to be such that for each layer name and layer idx, i know the bit-width to use. 

however, when i index data[0]['self_attn.q_proj'], i see a list of integers rather than just one. should i be selecting the last integer to know the final bit-width to use? 

```
import torch

# Load the .pt file
file_path = r"data\Meta-Llama-3-8B.pt"
data = torch.load(file_path)

print(type(data))
print(data.keys() if isinstance(data, dict) else data)

results = []

for idx, layer_data in data.items():
    for key, values in layer_data.items():
        # Extract the last value from the list
        value = values[-1]
        results.append({'idx': idx, 'key': key, 'value': value})

import pandas as pd
tmp = pd.DataFrame(results)
tmp['value'].mean()
```
