### ISSUE TITLE
Does it support the LLAMA3-8B-INSTRUNCT and QWEN2-7B-INSTRUCT?

### ISSUE THREAD

**Issue by LiMa-cas** [Aaronhuang-778/SliM-LLM#4]
Does it support the LLAMA3-8B-INSTRUNCT and QWEN2-7B-INSTRUCT?  What should I do if I want use only 4 bit quantization？is the multi-precision reference slower when dequantization need to detecte if use 2bit or 3bit or 4bit？

**Comment by LiMa-cas** [comment]
another question，  File "/extra_data/miniconda3/envs/slimllm/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 147, in forward
    inv_freq_expanded = self.inv_freq[None, :, None].float().expand(position_ids.shape[0], -1, 1)
AttributeError: 'NoneType' object has no attribute 'shape' thanks in advance

**Comment by Aaronhuang-778** [comment]
SliM-LLM dose supports LLAMA3-8B-INSTRUNCT quantization (which is not much different from LLAMA3-8B). We do not support QWEN2-7B-INSTRUCT yet, but this support will be considered in the future.

You can still set the `4bit` in the script to get 4-bit mixed-precision results, but we noticed that the quantization loss of the GPTQ 4-bit model is very marginal compared to FP16. Using 4-bit mixed-precision may not be able to get the same performance improvement as 2/3-bit, so SliM-LLM mainly focuses on 2/3-bit background. 

Mixed-precision hardware optimization is a challenging task that inevitably brings additional overhead, but a small sacrifice in inference speed at 2/3-bit can be exchanged for a significant improvement in model accuracy. Mixed-precision hardware speed optimization is also an interesting task we need to optimize in the future.

**Comment by LiMa-cas** [comment]
thanks a lot, another question is there is only pt file after slim quantization without config file and safetensors and in my opinion, this is different from the anchor. how could I use this pt file to inference a quantizationed LLAMA3?

**Comment by LiMa-cas** [comment]
how to convert the pt to hf file？

**Comment by LiMa-cas** [comment]
how to inference the slimllm with the pt?
