### ISSUE TITLE
Cannot reproduce

### ISSUE THREAD

**Issue by haoming-codes** [Aaronhuang-778/SliM-LLM#5]
Thank you for the great work. Running
```
python run.py \
{your top file for LLaMA}/huggyllama/llama-7b wikitext2 3bit --groupsize 128 \
--device "cuda:0" --tasks piqa,arc_easy,arc_challenge,boolq,hellaswag,winogrande
```
I got 7.8 for wikitext2, whereas Table 1 reports 6.40. What could I be doing wrong? It appears that the bitwidth assignment I got is different from the one on [huggingface](https://huggingface.co/AaronHuangWei/SliM-LLM_group-precision/tree/main/block_precision_128_3bit).

**Comment by Aaronhuang-778** [comment]
Hi, please check the calibration data used in bit-width allocation. We find that the random selection of calibration data may slightly affect the final bit-width results, you can use the hugging-face results to reproduce the paper-reported results.

But it is weird that your PPL result is 7.8. In our experiments, the random selection of calibration data only caused a PPL fluctuation of about 0.2 in 3-bit.

**Comment by haoming-codes** [comment]
Thank you. Is there a specific seed I should try besides the default `seed=0`? I just tried freshly cloning the repo and running the above script again, and indeed the perplexity results are:
 - 7.82 for wikitext
 - 82.82 for PTB
 - 10.18 for C4
according to the log. My environment is python=3.10.13 and torch=2.2.0. Does either of these seem problematic? Thank you for your help.
